### ISSUE TITLE
Invalid characters allowed in username

### ISSUE THREAD

**Issue by jpcjr** [jpcjr/corvid#18]
Currently, usernames can take arbitrary characters that should be there, like slashes and spaces.

Ideally this would be validated at the User level, but User validation is currently being done with forms (i.e. `RegistrationForm`).

**Comment by brenns10** [comment]
We can use a django `forms.ModelForm` to enforce the `User` field constraints on the form.  I'm working on a unit tests branch and I'll make this fix there.

**Comment by brenns10** [comment]
Fixed.
