### ISSUE TITLE
Themes!

### ISSUE THREAD

**Issue by jpcjr** [jpcjr/corvid#33]
Essential:
- [x] Add themes to project ([hint](https://github.com/getpelican/pelican-themes))
- [x] Have a way to add them to the database (hint: `populate.py`)
- [x] Implement `ChooseTheme` view
- [x] Add to Site Generation

Nice to Have:
- [ ] Map folder names to a nice theme title.
- [ ] Render a preview image and display it on the `ChooseTheme` view.

**Comment by brenns10** [comment]
Something to consider: we may want to have an (optional) image in the Theme model so that users can choose a theme based on something other than the name.  If we have a management script that adds themes, we could try to implement this as part of the script.  It would be interesting.

**Comment by brenns10** [comment]
This is implemented to our satisfaction now.  I will add the "nice to have's" in a separate bug.
