### ISSUE TITLE
Live Previewing

### ISSUE THREAD

**Issue by brenns10** [jpcjr/corvid#42]
This is something we promised in the requirements.  We were rather vague, so we can satisfy the requirements in two ways: whole site generation, or just page/post previewing (GitHub style).

1. For whole site generation, we have two options I see for implementation:

  - Storing generated sites, and just serving them.
  - Storing ZIPS in the database, and extracting files on demand to serve.

  Both of these options require us to have an "update" strategy so we're always serving up-to-date info.  We probably would have to go with one of the following strategies:

  - On each change, regenerate the site and update our stored copy.
  - On each request, check if the site was changed, and if so, update the stored copy before completing the request.

2. The alternative is page previewing, in which we shove a Javascript Markdown converter into the Edit Page view.  It would be all client side.

So the choice between these two options is a matter of how much time we have.  There's also the sticky situation of having a previewing subdomain and how we would get that all working in a production setup (to avoid malicious Javascript with access to all our site's cookies).

**Comment by jpcjr** [comment]
We have fulfilled option #2 with the addition of StackEdit, so I think we can close this issue.
