### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by jpcjr** [jpcjr/corvid#43]
Adding a Splash Screen with some basic info for prospective users would make our site seem friendlier.

**Comment by brenns10** [comment]
I assume you mean on the login page, for new users?  What would you like it to say?

I have:

> # Welcome to Corvid!
> Corvid is a website creation tool for the average person.

In a Bootstrapped jumbotron.

You may be able to view it here: http://home.brenns10.com depending on whether I'm doing the dev server.
