### ISSUE TITLE
Category selector in post create/update view will show categories that don't belong to this project.

### ISSUE THREAD

**Issue by brenns10** [jpcjr/corvid#53]
Ooops :)

**Comment by brenns10** [comment]
**GUYS WE NEED THIS FIXED OR OUR DEMO WILL BE AWFUL!**

**Comment by jpcjr** [comment]
they call me a rockstar, here to save the day
:guitar::guitar::guitar::guitar::guitar::guitar::guitar::guitar::guitar:

**Comment by brenns10** [comment]
# ** THERE GOES MY HERO **
:airplane:
