### ISSUE TITLE
Unmet Functional Requirements

### ISSUE THREAD

**Issue by jpcjr** [jpcjr/corvid#67]
From our SRS:

>13: Users will be able to upload custom templates for use with their website.
>14: Users will be able to add a number of plugins to their site...
>15: Users will be able to clone a project... [and] can select which elements are copied over to new project...
>17: Users will be logged out of the system after 2 hours of inactivity...

FR13 conflicts with our security requirement, so I say we ignore with justification.

So, we need to finish:
- [x] page plugins
- [x] project plugins
- [x] project cloning
- [x] inactivity logout

Each of these are issues in their own right, but they all need to be done by Friday.

**Comment by brenns10** [comment]
All functional requirements met?!?!

**Comment by jpcjr** [comment]
:raised_hands:
