### ISSUE TITLE
Possible to create a project that you can never navigate to

### ISSUE THREAD

**Issue by ajm188** [jpcjr/corvid#82]
Putting quotes or (I imagine) many other characters including &, ?, and the like in the project name, will prevent the user from ever navigating to that project, since these characters get escaped in the URL.

**Comment by brenns10** [comment]
Barring forward slash, there are no "invalid" characters in the URL, so long as we make sure our templates escape properly.  Thank you for the bug report!

**Comment by dealie16** [comment]
resolved by #87
