### ISSUE TITLE
Download zip fails on empty site

### ISSUE THREAD

**Issue by matthewbentley** [jpcjr/corvid#95]

**Comment by jpcjr** [comment]
Of course. Maybe we'll throw up a custom error message for an empty site. But it should still fail.

**Comment by brenns10** [comment]
To be fair, it didn't fail on empty sites before...

**Comment by jpcjr** [comment]
Well, you would get a zip, but Pelican throws error at empty content directories, so the zip is also empty. An error message is definitely my preferred handling method here.
